function [C, K, box] = optimizationConstraints()
    % optimizationConstraints
    % THE single source of truth for every constraint of the two-phase engine
    % optimization. No other file in the repository may define a numeric
    % constraint threshold: every module reads its limits from here, and
    % printConstraints renders this table at the start of every run.
    %
    % The constraints are listed one below the other in the binding order
    % C1..C14. Phase A holds everything computable on the normalized shape at
    % R_c = 1, with no knowledge of scale; phase B holds everything that needs
    % the actual engine size.
    %
    %   phase     "A"      normalized shape, R_c = 1
    %             "B"      sized engine
    %             "A+B"    enforced in both phases
    %   kind      "bound"      box bound on a decision variable
    %             "equation"   solved for, not searched (determines a size)
    %             "gate"       boolean admissibility test, no weight, no penalty
    %             "fixed"      not a variable at all
    %             "removed"    withdrawn, kept on record with the reason
    %
    % INPUT
    %   None
    % OUTPUT
    %   C   / struct / 1x14   Constraint table, in the binding order C1..C14.
    %                         Fields: id, phase, kind, name, quantity, lo, hi,
    %                         units, value, rationale
    %   K   / struct / 1x1    The same rows keyed by id, for named access from
    %                         the other modules: K.C10.lo, K.C10.hi, ...
    %   box / struct / 1x1    Search-box extents of the decision variables.
    %                         C4 is derived from these, so they live here too.

    % ------------ SEARCH BOX OF THE DECISION VARIABLES ------------
    box.x1 = [0.05, 0.99];         % [-]     phase A, inner apothem ratio ri/R_c
    box.N = [3, 18];               % [-]     phase A, number of star tips
    box.mdot_bracket = 0.30;       % [-]     phase B refines within +/-30% of the
                                   %         phase A flow

    % ------------ CONSTRAINTS, C1 TO C14 ------------
    C = struct("id", {}, "phase", {}, "kind", {}, "name", {}, "quantity", {}, ...
        "lo", {}, "hi", {}, "units", {}, "value", {}, "rationale", {}, ...
        "interaction", {});

    C(end+1) = row("C1", "A", "bound", "valid star", ...
        "h = x2 - x1/cos(pi/N)", 0, Inf, "-", "", ...
        ["Geometric: below h = 0 the tip radius falls inside the inner polygon" ...
         " vertex and the star does not exist. Reparametrizing (x1, x2) as" ...
         " (x1, h) turns the old linear inequality into this plain bound, so" ...
         " the optimum no longer sits on the face of a constraint."], ...
        ["Consumed by the phase A search box on h. Superseded in practice by C2," ...
         " which floors h strictly above zero, so C1 never binds on its own."]);

    C(end+1) = row("C2", "A", "bound", "tip resolvability", ...
        "h / h_grid", 5, Inf, "cells", "", ...
        ["The tip must be at least 5 grid cells tall, h_grid = R_c/grid_divisions." ...
         " In the current design the optimal tip is 1/36 of a cell: what is being" ...
         " optimized there is discretization noise, not geometry."], ...
        ["h_min = C2.lo/grid_divisions, the lower bound of h in the phase A box." ...
         " DEPENDS ON THE SEARCH GRID, NOT ON THE RE-RANKING GRID: with" ...
         " grid_search = 350 the floor is 0.01429, with grid_fine = 700 it is" ...
         " 0.00714, and the objective wants h -> 0, so the optimum sits exactly" ...
         " on whichever floor is in force. The shapes must therefore be" ...
         " RE-OPTIMIZED on the fine grid, not re-scored: a re-scored star would" ...
         " be ranked at twice the floor the ranking declares. This is also" ...
         " asymmetric between the shape families, because the cylinder has no h" ...
         " and no grid-derived bound at all: refining the grid moves the star" ...
         " and leaves the cylinder still, which biases the comparison in favour" ...
         " of the cylinder. C2 pulls against the objective, and against the" ...
         " fairness of the star-versus-cylinder comparison."]);

    C(end+1) = row("C3", "A", "bound", "containment", ...
        "max(x2, x1/cos(pi/N))", -Inf, 1, "-", "", ...
        "Geometric: the grain cannot stick out of the casing.", ...
        ["Consumed as the single linear inequality of the phase A search," ...
         " x1/cos(pi/N) + h <= 1. Pulls against C2: a taller tip forces a" ...
         " smaller port, and both cannot grow together."]);

    C(end+1) = row("C4", "A", "gate", "G_ox(0), anticipated in phase A", ...
        "G_ox(0) in phase A", NaN, NaN, "kg/(m2 s)", "", ...
        ["C10 applied already in phase A, on the flow the thrust requirement" ...
         " implies. Substituting R_c from C6 into G_ox(0) = mdot_ox/(R_c^2 Ap~(0))" ...
         " factorizes it exactly as Gox0 = C(mdot_ox)*Gtilde, with" ...
         " C = mdot_ox^(1/(2n+1))/(t_b a)^(2/(2n+1)) carrying all the scale and" ...
         " Gtilde = I~(b~_end)^(2/(2n+1))/Ap~(0) depending only on the normalized" ...
         " shape; with n = 0.75 the exponents are 0.4 and 0.8. mdot_ox is NOT a" ...
         " free variable: C7 nails it down through" ...
         " mdot_ox = F_target/mean_t[(1 + 1/O_F)*c_eff(O_F)], every term of which" ...
         " phase A already has. DO NOT go back to the existential form, 'does" ...
         " some mdot_ox in a search box put G_ox(0) in band': it approves shapes" ...
         " that only work at flows the thrust forbids, and phase A parks on that" ...
         " corner. Observed symptom: x1 stuck at 0.3468 and G_ox(0) = 255 against" ...
         " a floor of 400. The band is C10's, tightened by the margin below," ...
         " because phase A runs at a constant p_c = 20 bar and so gets mdot_ox" ...
         " wrong by a few percent. Derived, see below."], ...
        ["Consumed inside shapeMerit, level by level: an O/F level whose implied" ...
         " flow puts G_ox(0) out of band is discarded, and a shape survives only" ...
         " if some level does. THIS IS WHAT DECIDES THE PORT FRACTION x1: the" ...
         " objective is monotone in port size, so x1 has no interior optimum and" ...
         " ends up wherever C4 stops it. Pulls directly against the objective," ...
         " and depends on C7 (which fixes the flow) and on C6 (which fixes R_c)."]);

    C(end+1) = row("C5", "A+B", "gate", "O/F inside the CEA domain", ...
        "O/F(t), whole history", 1.1, 19.5, "-", "", ...
        ["Validity of the thermochemical lookup. Enforced over the WHOLE burn," ...
         " not just at t = 0: outside this range the interpolants are" ...
         " extrapolating and the performance numbers mean nothing."], ...
        ["Consumed twice: as a truncation of the burn (the upper crossing is one" ...
         " of the candidate ends of burn, together with C12 and burnout) and as" ...
         " the clamp on every thermochemical call. Bounds the lambda sweep of" ...
         " phase A from both sides, since the initial O/F must land inside it."]);

    C(end+1) = row("C6", "B", "equation", "burn time", ...
        "t_b", 300, 300, "s", "", ...
        ["Assignment, not negotiable. Solved for, not searched: it determines" ...
         " R_c through t_b = R_c^(2n+1) I~(b~_end)/(a mdot_ox^n)."], ...
        ["Consumed twice: as a closed form in phase A, where it gives R_c the" ...
         " moment mdot_ox is known, and as a bisection on R_c in sizeEngine." ...
         " Feeds C4 (through the scale factor) and C12 (which needs R_c to turn" ...
         " 3 mm into a normalized length). Depends on b~_end, which depends on" ...
         " C5 and C12, so the three are resolved together."]);

    C(end+1) = row("C7", "B", "equation", "thrust", ...
        "F", 50e3, 50e3, "N", "mean", ...
        ["Assignment. Determines the grain length L. Point (i) reads the 50 kN" ...
         " as the INITIAL thrust; the updated note allows reading them as the" ...
         " MEAN thrust when optimizing, in which case C9 becomes mandatory." ...
         " Which reading is in force is the 'value' field of this row:" ...
         " 'mean' or 'initial'. It is the only switch in the table."], ...
        ["Consumed twice: in phase A it FIXES THE OXIDIZER FLOW through" ...
         " mdot_ox = F/mean[(1 + 1/OF) c_eff], which is what makes C4 evaluable" ...
         " there; in phase B it is solved for L on a bracket. Pulls against C9:" ...
         " on the mean reading the initial thrust drifts upwards and can leave" ...
         " the 45-55 kN band. On the mean reading it also fixes the total" ...
         " impulse at F*t_b = 15 MNs regardless of shape, so maximizing Isp on" ...
         " the loaded mass becomes exactly minimizing that mass."]);

    C(end+1) = row("C8", "B", "equation", "peak chamber pressure", ...
        "max p_c", 20e5, 20e5, "Pa", "", ...
        ["Assignment: it is a ceiling, and the design leans on it because Isp" ...
         " grows with p_c. Determines the throat area," ...
         " A_t = max_b[mdot(b) cstar(b)]/p_target."], ...
        ["Consumed in sizeEngine, where p_c against A_t has an exact slope of -1" ...
         " and the update is a single division. Phase A does not solve it: it" ...
         " assumes p_c = 20 bar throughout, which is the approximation the 5 %" ...
         " margin of C4 exists to cover."]);

    C(end+1) = row("C9", "B", "gate", "initial thrust band", ...
        "F(0)", 45e3, 55e3, "N", "", ...
        ["Assignment. Mandatory whenever the 50 kN of C7 are read as a mean" ...
         " thrust rather than an initial one."], ...
        ["Consumed by feas_check in phase B only: phase A never checks it," ...
         " which is one of the ways a shape can pass A and fail B. Pulls" ...
         " against C7 on the mean reading, and tightens as the O/F drift grows," ...
         " since a larger drift means a larger spread between F(0) and F mean."]);

    C(end+1) = row("C10", "B", "gate", "initial oxidizer flux", ...
        "G_ox(0)", 400, 700, "kg/(m2 s)", "", ...
        ["THIS IS THE CONSTRAINT THAT CLOSES THE PROBLEM. Lower end: the value" ...
         " suggested by the assignment (500) and the validity of the regression" ...
         " correlation at start-up. Upper end: blow-off. Without the floor the" ...
         " optimum runs away to a 1 cm fuel annulus in a 3 m casing" ...
         " (G_ox(0) ~ 58). With it, G_ox(0) fixes r_0, R_c comes out of the burn" ...
         " time, and the geometry closes on its own."], ...
        ["Consumed by feas_check in phase B, and anticipated in phase A as C4." ...
         " Its floor ALWAYS BINDS, so it is what selects the port fraction; that" ...
         " is why the choice of 400 is justified with a curve (sweepGoxFloor)" ...
         " rather than with a weight. Pulls against the objective, which would" ...
         " rather have a larger port, and against C7, which caps the flow."]);

    C(end+1) = row("C11", "B", "gate", "numerical sanity", ...
        "G_ox(t), whole history", 10, Inf, "kg/(m2 s)", "", ...
        ["Not physics: rf = a G_ox^0.75 -> 0 stalls the ODE and the burn never" ...
         " terminates. A pure guard on the integrator."], ...
        ["Consumed by feas_check. Never binds once C10 holds, since the flux" ...
         " ends around 35 and the floor is 10. Kept as a guard, not as a design" ...
         " constraint."]);

    C(end+1) = row("C12", "B", "bound", "unburnt residual web", ...
        "web_residual", 3e-3, Inf, "m", "", ...
        ["The grain is not burnt until the casing is exposed: liner plus" ...
         " insulation have to survive. Without it the objective rewards a zero" ...
         " sliver that cannot be built."], ...
        ["Consumed as an END OF BURN, in both phases: b~_end is the first of the" ...
         " C5 crossing, this stop, and burnout. Needs R_c from C6 to become a" ...
         " normalized length, so the two are iterated together. It is what makes" ...
         " the sliver comparable between shape families, and therefore what" ...
         " carries the cylinder-versus-star margin: the star's tips reach the" ...
         " casing before its flats, so at a common 3 mm of thinnest web the star" ...
         " still has fuel left elsewhere."]);

    C(end+1) = row("C13", "B", "gate", "envelope", ...
        ["2*R_c", "L"], [-Inf, -Inf], [2.0, 12.0], "m", "", ...
        ["Safety net only. At G_ox(0) >= 200 the casing is 0.62 m across and" ...
         " about 6 m long, so this never binds, but it costs nothing to keep." ...
         " ASSUMPTION: the assignment gives no envelope; these two numbers are" ...
         " ours, sized to leave a wide margin on the expected design" ...
         " (~0.60 m x ~6.1 m). Change them here and nowhere else."], ...
        ["Consumed by feas_check. Does not bind on HTPB with an O/F near 2, but" ...
         " it is the constraint most likely to bite on the high-O/F oxidizers," ...
         " whose grains are much shorter but whose casings are wider. If it ever" ...
         " binds, the oxidizer ranking can invert, and that is a result to show" ...
         " rather than a failure."]);

    C(end+1) = row("C14", "-", "removed", "oxidizer: FREE", ...
        "oxidizer", NaN, NaN, "-", "", ...
        ["REMOVED, and kept in the table so the reason is on record. 'GOX' in" ...
         " the assignment always denotes the oxidizer mass FLUX G_ox" ...
         " [kg/(m2 s)], not gaseous oxygen: it appears as 'partire con" ...
         " GOX = 500 kg/m2s', which is a flux. The oxidizer is therefore a free" ...
         " parameter at point (i) too, 'nel limite della ragionevolezza', and" ...
         " the best one becomes the baseline directly. Symmetry argument: the" ...
         " geometry is not imposed at point (i) either, so neither is the" ...
         " oxidizer; the levers of point (iii) are changes with respect to the" ...
         " baseline the student picks. GASEOUS oxygen is nonetheless excluded" ...
         " on storage grounds: ~3 t of oxidizer in the gas phase at 200 bar" ...
         " needs over 10 m3 of high-pressure tankage, which is a test-bench" ...
         " oxidizer, not an upper stage. Use O2(L). Justifying that exclusion" ...
         " is part of the critical analysis the assignment asks for."], ...
        ["Nothing consumes it any more. The oxidizer is now enumerated by" ...
         " main_optimization over the WHOLE A -> B chain, because it moves the" ...
         " peak of Isp(O/F), hence the best O/F level, hence mdot_ox, hence" ...
         " G_ox(0), hence the window C4 leaves open on the port fraction."]);

    % ------------ C4: derived from C10, with the phase A margin ------------
    % Same band as C10, tightened on both sides. Phase A evaluates it on the
    % flow computed from the thrust requirement, not on a search box, so the
    % only slack it needs is the one covering its own approximation: a constant
    % p_c = 20 bar instead of the exact pressure history.
    margin = 1.05;                                       % [-] 5 %
    K = index_by_id(C);
    i4 = find([C.id] == "C4", 1);
    C(i4).lo = K.C10.lo * margin;                        % [kg/m2 s]
    C(i4).hi = K.C10.hi / margin;                        % [kg/m2 s]

    % Keyed view, rebuilt so it carries the derived C4
    K = index_by_id(C);
end

%% FUNCTIONS

function r = row(id, phase, kind, name, quantity, lo, hi, units, value, ...
        rationale, interaction)
    % row
    % Build one constraint record. Keeping this in one place is what makes the
    % table above readable as a table.
    % INPUT
    %   id          / string / 1x1   Constraint id, "C1".."C14"
    %   phase       / string / 1x1   "A", "B" or "A+B"
    %   kind        / string / 1x1   "bound", "equation", "gate", "fixed" or
    %                                "removed"
    %   name        / string / 1x1   Short human name
    %   quantity    / string / 1xQ   The constrained quantity, one per bound pair
    %   lo, hi      / double / 1xQ   Bounds; -Inf/+Inf one-sided, NaN if derived
    %   units       / string / 1x1   Units of the bounds
    %   value       / string / 1x1   Fixed value (kind == "fixed"), "" otherwise
    %   rationale   / string / 1xR   Why the constraint exists (parts joined)
    %   interaction / string / 1xR   Who consumes it and what it pulls against
    % OUTPUT
    %   r           / struct / 1x1   One row of the constraint table

    r = struct();
    r.id = string(id);
    r.phase = string(phase);
    r.kind = string(kind);
    r.name = string(name);
    r.quantity = string(quantity);
    r.lo = lo;
    r.hi = hi;
    r.units = string(units);
    r.value = string(value);
    r.rationale = strjoin(string(rationale), "");
    r.interaction = strjoin(string(interaction), "");
end

function K = index_by_id(C)
    % index_by_id
    % Build the id-keyed view of the constraint table, so the other modules can
    % read K.C10.lo instead of a magic array index.
    % INPUT
    %   C / struct / 1xM   Constraint table
    % OUTPUT
    %   K / struct / 1x1   One field per constraint id

    K = struct();
    for i = 1:numel(C)
        K.(char(C(i).id)) = C(i);
    end
end
